plugins:
  - node

extends:
  - eslint:recommended
  - plugin:node/recommended

parser: babel-eslint
parserOptions:
  sourceType: module

env:
  node: true
  es6: true
  mocha: true

rules:
  # possible errors
  no-console:
    - warn
  no-constant-condition:
    - warn
  no-dupe-args:
    - warn
  no-dupe-keys:
    - warn
  no-debugger:
    - warn
  no-duplicate-case:
    - warn
  no-extra-boolean-cast:
    - warn
  no-extra-parens:
    - warn
  no-extra-semi:
    - warn
  no-inner-declarations:
    - warn
    - both
  no-irregular-whitespace:
    - warn
  no-unreachable:
    - warn

  # style
  array-bracket-spacing:
    - warn
    - never
  block-spacing:
    - warn
    - always
  brace-style:
    - warn
    - 1tbs
    - allowSingleLine: false
  camelcase:
    - warn
    - properties: always
  comma-spacing:
    - warn
    - before: false
      after: true
  comma-style:
    - warn
    - last
  indent:
    - warn
    - 2
    - SwitchCase: 1
  key-spacing:
    - warn
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing:
    - warn
    - before: true
      after: true
  new-parens:
    - warn
  newline-per-chained-call:
    - warn
    - ignoreChainWithDepth: 4
  no-continue:
    - warn
  no-inline-comments:
    - warn
  no-lonely-if:
    - warn
  no-mixed-spaces-and-tabs:
    - warn
  no-multiple-empty-lines:
    - warn
    - max: 1
      maxBOF: 0
      maxEOF: 1
  no-negated-condition:
    - warn
  no-new-object:
    - warn
  no-restricted-syntax:
    - warn
    - WithStatement
  no-spaced-func:
    - warn
  no-trailing-spaces:
    - warn
    - skipBlankLines: true
  no-whitespace-before-property:
    - warn
  object-curly-spacing:
    - warn
    - always
  padded-blocks:
    - warn
    - never
  quote-props:
    - warn
    - as-needed
    - keywords: false
  quotes:
    - warn
    - double
    - allowTemplateLiterals: true
  semi:
    - warn
    - always
  semi-spacing:
    - warn
    - before: false
      after: true
  space-before-blocks:
    - warn
    - always
  space-before-function-paren:
    - warn
    - anonymous: always
      named: never
  space-in-parens:
    - warn
    - never
  space-unary-ops:
    - warn
    - words: true
      nonwords: false
  spaced-comment:
    - warn
    - always

  # best practices
  complexity:
    - warn
    - 20
  curly:
    - off
  dot-location:
    - warn
    - property
  eqeqeq:
    - warn
    - smart
  guard-for-in:
    - warn
  no-alert:
    - warn
  no-caller:
    - warn
  no-case-declarations:
    - warn
  no-else-return:
    - warn
  no-eval:
    - warn
  no-labels:
    - warn
  no-lone-blocks:
    - warn
  no-loop-func:
    - warn
  no-multi-spaces:
    - warn
    - exceptions:
        VariableDeclarator: true
  no-octal:
    - warn
  no-sequences:
    - warn
  no-void:
    - warn
  no-warning-comments:
    - warn
    - terms:
        - fix
        # unprofessional
        - shit
        - fuck
      location: anywhere
  no-with:
    - warn
  vars-on-top:
    - warn
  # lol
  yoda:
    - warn
    - never

  # variables
  no-catch-shadow:
    - warn
  no-label-var:
    - warn
  no-shadow-restricted-names:
    - warn
  no-undef:
    - warn
  no-undefined:
    - warn
  no-unused-vars:
    - warn

  # es6
  arrow-parens:
    - warn
    - always
  arrow-spacing:
    - warn
    - before: true
      after: true
  constructor-super:
    - warn
  no-class-assign:
    - warn
  no-confusing-arrow:
    - warn
  no-dupe-class-members:
    - warn
  no-this-before-super:
    - warn
  object-shorthand:
    - warn
    - always
  prefer-arrow-callback:
    - warn
  prefer-template:
    - warn
  template-curly-spacing:
    - warn
    - never
  no-var:
    - warn
  id-length:
    - warn
    - min: 2
      properties: never
      exceptions:
        - $

  # node
  node/no-unsupported-features/es-syntax:
    - off
